### ISSUE TITLE
Not synchronizing

### ISSUE THREAD

**Issue by Redsandro** [NemProject/NemCommunityClient#462]
I'm running both NIS and NCC on Linux with the Standalone Client. I've been away for a while. Then I checked my wallet. But it's not updating.

> NIS is synchronizing. At block 880748, est. 104 days behind. (at block 880748)

I've updated to from `0.6.79` to `0.6.84` to see if that fixes things, but still staying at the same block.

Any suggestions?

**Comment by evias** [comment]
You can import the bootstrapped chain:
http://bob.nem.ninja/nis5_mainnet-1002k.h2.db.zip   

Unzip this in your home /home/foo/nem/nis/data folder 

This will set your node after-fork.

**Comment by Redsandro** [comment]
Thank you @evias. I guess I was on an unsupported fork. Nuked the database. Now I'm synched again. :+1:
